version: '3'
services:

  backend:
    build: ./FenderBackend
    container_name: backend-detection
    command: uvicorn main:app --host 0.0.0.0  --port 80 --reload
    ports:
      - 3000:80
    volumes:
      - ./FenderBackend/src:/app/src
