name: publish
on: [push]
jobs:
  publish-fender-backend-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker-Compose Publish
        uses: pennsignals/publish_docker-compose@v0.1.1
        with:
          version: '0.2.6-rc.1'
          docker_compose: 'compose.yaml' # required
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
